### ISSUE TITLE
Consider use of PathLib

### ISSUE THREAD

**Issue by anapaulagomes** [anapaulagomes/looong#9]
Reference: http://pbpython.com/pathlib-intro.html

**Comment by hilam** [comment]
This It's a great project at all. I can work on this issue, if you consider yet. And, in the Click part of TODO.

**Comment by anapaulagomes** [comment]
Go for it. :) @hilam Please try to work on each one at a time. Thanks.

**Comment by hilam** [comment]
Sure. Thanks too.

**Comment by hilam** [comment]
@anapaulagomes Before proceeding with the work, need a definition: should I adapt the code to support earlier Python  versions or will version 3.6 be a minimum requirement? It happens that only from version 3.6, every standard library was adapted to work with pathlib.Path objects.

**Comment by anapaulagomes** [comment]
@hilam I haven't thought about it before but I think would be good keeping the compatibility with Python previous versions. That said, I think doesn't make sense adding Pathlib for now. Thanks!
